<a href="https://colab.research.google.com/github/Aswinramesh04/100-DaysOfCode-DataScience/blob/main/Day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                                    **Numpy**        --Loga Aswin
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.                                    

In [2]:
import numpy as np

In [3]:
#checking version
print(np.version)

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>


**Creating Array**

In [6]:
#1D Array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

#2D Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

# Higher dimensional Array
arr = np.array([10, 20, 30, 40], ndmin=5)

print(arr)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[[[[[10 20 30 40]]]]]


**Array Slicing**

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[-4:-2])


[2 3 4 5]
[4 5]


**NumPy Function**: insert():

Insert values at given place.

In [9]:
a = np.array([1,2,3,4,5])
a = np.insert(a, 2, 100)
print(a)

[  1   2 100   3   4   5]
