<a href="https://colab.research.google.com/github/Aswinramesh04/100-DaysOfCode-DataScience/blob/main/Day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                                    **Numpy**        --Loga Aswin
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.                                    

In [2]:
import numpy as np

In [3]:
#checking version
print(np.version)

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>


**Creating Array**

In [6]:
#1D Array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

#2D Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

# Higher dimensional Array
arr = np.array([10, 20, 30, 40], ndmin=5)

print(arr)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[[[[[10 20 30 40]]]]]


**Array Slicing**

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[-4:-2])


[2 3 4 5]
[4 5]


**NumPy Function**: insert():

Insert values at given place.

In [9]:
a = np.array([1,2,3,4,5])
a = np.insert(a, 2, 100)
print(a)

[  1   2 100   3   4   5]


In [10]:
#Numpy data types:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64



Copy creates a new array, independent of the original, while view merely represents the original array. Copies are separate, preserving data isolation, while views share data, causing changes in one to impact the other.

**COPY:**

In [11]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


View:

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


NumPy Array Iterating

In [16]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


**Joining NumPy Arrays**

In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


**Using Stack function **

In [23]:
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[10 40]
 [20 50]
 [30 60]]


**Splitting the array**

In [26]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new = np.array_split(arr, 2)
print(new)

[array([1, 2, 3]), array([4, 5, 6])]


**Searching Array**

In [33]:
import numpy as np
arr = np.array([10, 20, 30, 40, 55, 45, 4])
x = np.where(arr == 5)
y = np.where(arr%2 == 0)
z = np.where(arr%2 == 1)
print(x)
print(y)
print(z)

(array([], dtype=int64),)
(array([0, 1, 2, 3, 6]),)
(array([4, 5]),)


**Sorting**

In [35]:
import numpy as np

arr = np.array([3, 2, 0, 1])
arr1 = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))
print(np.sort(arr1))

[0 1 2 3]
['apple' 'banana' 'cherry']


**Filter**

In [37]:
import numpy as np

arr = np.array([41, 40, 42, 43, 44])

x = [True, True, False, True, False]

newarr = arr[x]

print(newarr)

[41 40 43]
